name: nucliseg # to update an existing environment: conda env update -n <current_name> --file <path-to-this-file>
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13
  - pytorch-cuda=11.7
  - torchvision
  - opencv-python
  - scikit-image
  - pip
  - pip:
    - setuptools==59.5.0
    - -e .